### ISSUE TITLE
Buy X Sellable-Items in range get Y % off

### ISSUE THREAD

**Issue by kazimnami** [kazimnami/Sitecore.Commerce.Promotions#16]
Using Tags potentially 

Buy X amount of pieces in a range and get Y% off.  E.g. Buy 7 pieces get 10% off, Buy 8 pieces get 20% off (The more items you buy the more you save)

**Comment by andrew-sutherland-sitecore** [comment]
@kazimnami do you envisage this promotion to utilise the Grid ui to create a tiered list of promotional benefits? (e.g. similar to tiered pricing)

I can investigate whether we have the ability to add support for new data types to the IRuleValue if that's the case.

**Comment by kazimnami** [comment]
I was wondering if we could just use the multi benefit approach for this
e.g. have one benefit that can be added multiple times with different
settings e.g.
Benefits:
Apply benefit for itemX quantity between 3 and 4 (inclusive) at 5% off
Apply benefit for itemX quantity between 5 and 6 (inclusive) at 10% off

so basically each quantity will have this discount applied:
1 - no disocunt
2 - no discount
3 - 5% off
4 - 5% off
5 - 10% off
6 - 10% off

does that make sense?

-Kaz

**Comment by ajsuth** [comment]
Ah, yes! Much simpler that way.

The title and initial comment, _Using Tags potentially_, also led me to believe we were also looking to buy X quantity of products from selected product range to get Y% off. It might also be worth looking at this scenario in a new issue.

**Comment by ajsuth** [comment]
In the current implementation, we can use the _Cart Item Quantity is in [min] [max] Range?_ qualification to specify the quantity outer limits and use one or more of the new CartItemQuantityRangePercentOffAction benefits to specify sub-ranges to apply "The more items you buy the more you save".

**Comment by kazimnami** [comment]
Nice one!
