### ISSUE TITLE
Buy X quantity for Y price

### ISSUE THREAD

**Issue by kazimnami** [kazimnami/Sitecore.Commerce.Promotions#2]
e.g. Buy 2 for $40

**Comment by andrew-sutherland-sitecore** [comment]
The BOGO description may apply to separate promotion types, which we can create other issues to manage.

A quick summary of promotions and their inputs:

BX4Y Fixed Price
- QuantityX
- Price
- MaximumApplications

BXGY Fixed Price
- QuantityX
- QuantityY
- Price
- MaximumApplications

BXGY $ Discount
- QuantityX
- QuantityY
- Discount
- MaximumApplications

BXGY % Discount
- QuantityX
- QuantityY
- DiscountPercentage
- MaximumApplications

**Comment by andrew-sutherland-sitecore** [comment]
Reopening as closed by accident
