### ISSUE TITLE
Unable to create custom qualification when input field is DateTime Picker

### ISSUE THREAD

**Issue by ajsuth** [kazimnami/Sitecore.Commerce.Promotions#35]
For qualifications that use the DateTime Picker, the following error displayed to the user.
> Error:  Promotion '<Promotion Book Name> - <Promotion item name>' cannot be built. Please check the qualifications and benefits.

This only affects qualifications. Benefits are unaffected.

**Comment by andrew-sutherland-sitecore** [comment]
This issue was addressed as part of the commit for #24 _Provide support for Boolean rule values in qualifications and benefits_.
